name: siderouting
description: A responsive web page with sidemenu and routing

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_web: ^0.2.2+3
  webview_flutter_platform_interface: ^2.7.0
  provider: ^6.1.1
  url_launcher: ^6.1.14
  http: ^1.1.2
  hyphenatorx: ^1.5.9
  shared_preferences: ^2.2.2
  beamer: ^1.5.6
  photo_view: ^0.14.0
  image_downloader_web: ^2.0.4
  word_generator: ^0.4.3
  flutter_launcher_icons: ^0.13.1
  #flutter_side_menu: ^0.4.0
  flutter_side_menu:
    git:
      url: https://github.com/wendellavila/flutter_side_menu
      ref: main # branch name

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/icons/
    - assets/img/logo/
    - assets/img/photos/
    - assets/placeholder/
    - assets/json/
    - assets/google_fonts/
